[package]
name = "sgdk-bintos"
version.workspace = true
edition.workspace = true
description = "Binary to GAS assembly source converter for SGDK"

[[bin]]
name = "bintos"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
